AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Change instance type as needed
      ImageId: ami-0c55b159cbfafe1f0  # Replace with a valid AMI ID for your region
      KeyName: my-key-pair  # Replace with your existing EC2 key pair
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allow SSH (change for security)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allow HTTP access
      Tags:
        - Key: Name
          Value: MySecurityGroup

Outputs:
  InstanceId:
    Description: Instance ID of the created EC2 instance
    Value: !Ref MyEC2Instance
